name: simple-fetch
run-name: ${{ github.actor }} is testing GitHub actions to fetch/write
env:
  PYTHON_VERSION: "3.10"
  AUTOMATION_USERNAME: "AFP Automation"
  AUTOMATION_EMAIL: "automation@afp.com"

on: [push]
jobs:
  fetch-save-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: |
          python simple-fetch.py
      - name: Log date
        run: |
          date > published.txt
      - name: Commit data
        run: |
          git config --global user.name $AUTOMATION_USERNAME
          git config --global user.email $AUTOMATION_EMAIL
          git add .
          git commit -m "Updating data"
          git push